### PR TITLE
New: Generate random test users file if no name is specified

### PR DESCRIPTION
**Pull request by mheap**

### CODE REVIEW

**Comment by mheap** [comment]
This isn't ready to merge yet, as it tries to read the temp file and bails out. We need to create the file if it does not exist

**Comment by stuartherbert** [comment]
One alternative is to just generate random users inside the story / template. That way, the generated users will fit the system under test.

**Comment by stuartherbert** [comment]
Could you provide more details on what the backwards-compatibility break is that this fixes? Thanks.

**Comment by mheap** [comment]
Existing tests that do not depend on users will now not run without a users file specified.

If no users file is specified, I'd expect the test to run with an empty user list.

As previously discussed, if the test creates any users I'd expect them to be persisted to the generated file

**Comment by stuartherbert** [comment]
I didn't know that was the bug :)

I've just pushed branch hotfix/2.0.2 to Github. Can you checkout this branch and confirm if it solves the problem, please?

If --users switch not used, nothing should happen.

If --users file not found, a warning will be printed. 

If --users file empty, a warning will be printed. 

Ta,
Stu
--

**Pull request closed without merging**
